name: OpenAPI Validation

on:
  push:
    branches: [ master, v12, v14, v15 ]
  pull_request:
    branches: [ master, v12, v14, v15 ]


jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate example specification
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: example/example.swagger.yaml
