name: OpenAPI Validation

on:
  push:
    branches: [ master, v8, v9 ]
  pull_request:
    branches: [ master, v8, v9 ]


jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate against OpenAPI 3.0
        uses: char0n/apidom-validate@v1
        with:
          definition-file: example/example.documentation.3.0.yaml
      - name: Validate against OpenAPI 3.1
        uses: char0n/apidom-validate@v1
        with:
          definition-file: example/example.documentation.3.1.yaml
